config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'lotteries#index'

  get 'result', to: 'lotteries#result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lotteries_controller.rb
class LotteriesController < ApplicationController
  def index; end

  def result
    filename = 'input.txt'
    data = {}

    File.open(filename).each do |line|
      line = line.strip.split ','
      data[line[0].to_s+ ','+line[1].to_s+','+line[2].to_s] = line.last.to_s
    end

    winning_number = params[:winning_number]
    result = []

    data.each do |d|
      res = Array.new(winning_number.length + 1) {Array.new(d[1].length + 1, '')}

      winning_number.each_char.with_index do |win, i|
        d[1].each_char.with_index do |d1, j|
          res[i+1][j+1] = if win == d1
                            res[i][j] + win
                          else
                            [res[i][j+1], res[i+1][j]].max_by(&:length)
                          end
        end
      end

      credits = res[-1][-1].length

      if credits > 0
        result << d[0] + ',' + credits.to_s
      end


    end

    @result = result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lotteries_helper.rb
module LotteriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lottery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lotteries/index.html.erb
<h1>Welcome to the LCS Lottery!</h1>

<%= form_with(url: result_path, method: "get") do |form| %>

  <%= form.label :winning_number, "Input winning number" %>
  <%= form.text_field :winning_number %><br>

  <%= form.submit "Result" %>
<% end %>

app/views/lotteries/result.html.erb
<h1>Output result:</h1>
<% @result.each do |res| %>
  <%= res %><br>
<% end %>